model:
  dir: "assets/model"
  current:
    name: attnet
  attsubnet:
    weights: "gru_weights_attn_sub.h5"
    preprocessor: "preprocessor_attn.pkl"
    architecture: "gru_architecture_attn_sub.json"
  attnet:
    weights: "gru_weights_attn.h5"
    preprocessor: "preprocessor_attn.pkl"
    architecture: "gru_architecture_attn.json"

data:
  dir: "assets/data"
  city: "Toronto_dataset.csv"
  geojson: "toronto-top-100-restaurants.geojson"
  source: "restaurant_reviews_small.csv"
  train: "reviews_train_small.csv"
  test: "reviews_test_small.csv"
  businesses: "business.json"
  reviews: "review.json"

constants:
  VOCAB_MAX_FEATURES: 100000
  WORD_MAX_LEN: 100
  BATCH_SIZE: 128
  TOP_COUNT: 100
  REVIEWS_PER_BUSINESS: 20
  BUSINESS_TYPE: Restaurant
  CITY: Toronto
