model:
  dir: "assets/model"
  utils:
    preprocessor: "preprocessor.pkl"
  current:
    name: quora
  attsubnet:
    weights: "gru_weights_attn_sub.h5"
    architecture: "gru_architecture_attn_sub.json"
  attnet:
    weights: "gru_weights_attn.h5"
    architecture: "gru_architecture_attn.json"
  quora:
    weights: "weights_quora3.h5"
    architecture: "architecture_quora3.json"

data:
  dir: "assets/data"
  city: "Toronto_dataset.csv"
  city_matrix: "town_similarity_matrix.pkl"
  geojson: "toronto-top-100-restaurants.geojson"
  source: "restaurant_reviews.csv"
  train: "reviews_train.csv"
  test: "reviews_test.csv"
  businesses: "business.json"
  reviews: "review.json"

constants:
  VOCAB_MAX_FEATURES: 100000
  WORD_MAX_LEN: 100
  BATCH_SIZE: 128
  TOP_COUNT: 100
  REVIEWS_PER_BUSINESS: 20
  BUSINESS_TYPE: Restaurant
  CITY: Toronto
